// ============================================================
//  exportUtils.js — Centralized Excel Export Utility
//  Uses branding.js for company name, sheet styling, etc.
//  Dependency: xlsx (already in package.json)
//  Usage: exportToExcel({ title, columns, rows, extraInfo })
// ============================================================

import * as XLSX from 'xlsx';
import branding from '../config/branding';

/**
 * Exports data to a styled Excel (.xlsx) file with company branding in header.
 *
 * @param {Object} options
 * @param {string}   options.title       - Sheet/document title (used as filename & sheet name)
 * @param {string[]} options.columns     - Column header labels
 * @param {Array[]}  options.rows        - 2D array or array-of-objects matching column order
 * @param {Object}   [options.extraInfo] - Key-value metadata shown above the table
 * @param {string}   [options.filename]  - Override the auto-generated filename
 */
export function exportToExcel({ title, columns = [], rows = [], extraInfo = {}, filename }) {
  const company = branding.company;
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB').replace(/\//g, '-');
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  const safeTitle = title.replace(/[^a-zA-Z0-9 _-]/g, '').trim().replace(/\s+/g, '_');
  const outputFile = filename || `${safeTitle}_${dateStr}.xlsx`;

  const wb = XLSX.utils.book_new();
  const ws_data = [];

  // ---- Branding Header Rows ----
  ws_data.push([company.name]);
  ws_data.push([company.tagline]);
  if (company.phone || company.email) {
    ws_data.push([`Phone: ${company.phone || ''}   Email: ${company.email || ''}`]);
  }
  if (company.address) {
    ws_data.push([`Address: ${company.address}`]);
  }
  ws_data.push([]); // empty row
  ws_data.push([`${title}`]);
  ws_data.push([`Exported: ${dateStr} ${timeStr}`]);
  ws_data.push([]); // empty row

  // ---- Extra Info Rows ----
  const extraEntries = Object.entries(extraInfo);
  if (extraEntries.length > 0) {
    extraEntries.forEach(([k, v]) => ws_data.push([`${k}: ${v}`]));
    ws_data.push([]); // empty row
  }

  // ---- Column Headers ----
  ws_data.push(columns);

  // ---- Data Rows ----
  rows.forEach(row => {
    if (Array.isArray(row)) {
      ws_data.push(row);
    } else {
      ws_data.push(Object.values(row));
    }
  });

  // ---- Empty row + footer ----
  ws_data.push([]);
  ws_data.push([branding.document.footerText || `Generated by ${company.shortName}`]);

  const ws = XLSX.utils.aoa_to_sheet(ws_data);

  // ---- Column widths (auto-size) ----
  const colWidths = columns.map((col, i) => {
    const maxLen = Math.max(
      col.length,
      ...rows.map(row => {
        const val = Array.isArray(row) ? row[i] : Object.values(row)[i];
        return val != null ? String(val).length : 0;
      })
    );
    return { wch: Math.min(Math.max(maxLen + 4, 12), 40) };
  });
  ws['!cols'] = [{ wch: 40 }, ...colWidths]; // first col wider for branding text

  XLSX.utils.book_append_sheet(wb, ws, safeTitle.slice(0, 31));
  XLSX.writeFile(wb, outputFile);
}
